name: Team Hellhounds
favicon: null
layout_spectrum: 0.21909422567114234
typography_spectrum: 0.2776504149660468
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.07040882762521505
  lightness: 0.4614664064720273
  saturation: 0.0764462286606431
  rhythmicContrast: 0.182838867418468
purpose: []
